### ISSUE TITLE
Windows networking issue

### ISSUE THREAD

**Issue by arthurrichards77** [StarlingUAS/example_python_controller#3]
Running the Fenswood AP compose stack kept getting "no namespaces found" on Windows.  Got it to work by creating the alternative compose file below, essentially commenting out the "network_mode" bit:

```
version: '3'

services:
  controller:
    build: example_controller_python_ap/
    # network_mode: bridge
    command: ["ros2", "launch", "example_controller_python", "fenswood_example.launch.py"]


networks:
  default:
    external: true
    name: fenswoodscenario_default
```
